language: node_js
script:
 - echo "Deploy!"
install:
  - npm install -g firebase-tools
  - npm install
  - npm run build
after_success:
  - firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
